## 列表推导式和生成器表达式

### 基于一个字符串构建一个 Unicode 码点列表

In [1]:
symbols = '$¢£¥€¤'
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

codes

[36, 162, 163, 165, 8364, 164]

### 使用列表推导式基于一个字符串构建一个 Unicode 码点列表

In [2]:
symbols = '$¢£¥€¤'

codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

#### 列表推导式和生成器表达式的局部作用域

In [3]:
x = 'ABC'
codes = [ord(x) for x in x]
x

'ABC'

In [4]:
codes

[65, 66, 67]

In [5]:
# python 3.10
# codes = [last := ord(c) for c in x]
# last

### 使用列表推导式和 map/filter 组合构建同一个列表

In [6]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

[162, 163, 165, 8364, 164]

In [7]:
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

### 使用列表推导式计算笛卡儿积

In [8]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [9]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [10]:
# 加个换行提升可读性
tshirts = [(color, size) for color in colors 
           for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

### 使用生成器表达式构建一个元组和一个数组

In [11]:
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [12]:
import array

array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

### 使用生成器表达式计算笛卡儿积

In [13]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


## 元祖不仅仅是不可变列表

### 把元组当作记录使用

In [14]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokey', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [15]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


### 用作不可变列表

In [16]:
a = (10, 'alpha', [1,2])
b = (10, 'alpha', [1,2])
a == b

True

In [17]:
b[-1].append(99)
a == b

False

In [18]:
b

(10, 'alpha', [1, 2, 99])

In [19]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True


tf = (10, 'alpha', (1,2)) # 不包含可变元素
tm = (10, 'alpha', [1,2]) # 包含可变元素 list
fixed(tf)

True

In [20]:
fixed(tm)

False

## 序列和可迭代对象拆包

### 并行赋值

In [21]:
lax_corrdinates = (33.9425, -118.408056)
latitude, longitude = lax_corrdinates # unpacking
latitude

33.9425

In [22]:
longitude

-118.408056

In [23]:
# divmod() 函数把除数和余数运算结果结合起来，返回一个包含商和余数的元组(a // b, a % b)
divmod(20, 8)

(2, 4)

In [24]:
t = (20, 8)
divmod(*t)

(2, 4)

In [25]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [26]:
import os

_, filename = os.path.split('/home/planning/.ssh/id_rsa.pub')
filename

'id_rsa.pub'

### 使用 * 获取余下的项

In [27]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [28]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [29]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [30]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [31]:
*head, b , c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

### 在函数调用和序列字面量中使用 * 拆包

In [32]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest


fun(*[1, 2], 3, *range(4,7))

(1, 2, 3, 4, (5, 6))

In [33]:
*range(4), 4

(0, 1, 2, 3, 4)

In [34]:
[*range(4), 4]

[0, 1, 2, 3, 4]

In [35]:
{*range(4), 4, *(5, 6, 7)}

{0, 1, 2, 3, 4, 5, 6, 7}

### 嵌套拆包

#### 拆包嵌套元组，获取经度

In [36]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),  # <1>
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

In [37]:
print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
for name, _, _, (lat, lon) in metro_areas:  # <2>
    if lon <= 0:  # <3>
        print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


## 序列模式匹配

### 假想的 Robot 类中的方法

In [38]:
# Python 3.10 支持
# def handle_command(self, message):
#     match message:
#         case ['BEEPER', frequency, times]:
#             self.beep(times, frequency)
#         case ['NECK', angle]:
#             self.rotate_neck(angle)
#         case ['LED', ident, intensity]:
#             self.leds[ident].set_brightness(ident, intensity)
#         case ['LED', ident, red, green, blue]:
#             self.leds[ident].set_color(ident, red, green, blue)
#         case _:
#             raise InvalidCommand(message)

In [39]:
# match / case 语法

## 切片

### 为什么切片和区间排除最后一项

In [40]:
l = [10, 20, 30, 40, 50, 60]

l[:2]  # split at 2

[10, 20]

In [41]:
l[2:]

[30, 40, 50, 60]

In [42]:
l[:3]  # split at 3

[10, 20, 30]

In [43]:
l[3:]

[40, 50, 60]

### 切片对象

In [44]:
s = 'bicycle'
s[::3]

'bye'

In [45]:
s[::-1]

'elcycib'

In [46]:
s[::-2]

'eccb'

#### 从纯文本形式的发票中提取商品信息

In [47]:
invoice = """
0.....6.................................40........52...55........
1909 Pimoroni PiBrella                      $17.50    3    $52.50
1489 6mm Tactile Switch x20                  $4.95    2    $9.90
1510 Panavise Jr. - PV-201                  $28.00    1    $28.00
1601 PiTFT Mini Kit 320x240                 $34.95    1    $34.95
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   imoroni PiBrella                  
     $4.95   mm Tactile Switch x20             
    $28.00   anavise Jr. - PV-201              
    $34.95   iTFT Mini Kit 320x240             
 


### 为切片赋值

In [48]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [50]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [51]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [52]:
# 如果赋值对象是一个切片，那么右边必须是可迭代对象
try:
    l[2:5] = 100
except TypeError as e:
    print(repr(e))

TypeError('can only assign an iterable',)


In [53]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

## 使用 + 和 * 处理序列

In [54]:
l = [1, 2, 3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [55]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

### 构建嵌套列表

#### 一个列表中嵌套 3 个长度为 3 的列表，可以表示井字游戏棋盘

In [56]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [57]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

#### 不能在一个列表中 3 次引用同一个列表

In [58]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [59]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

### 使用增量赋值运算符处理序列

In [60]:
l = [1, 2, 3]
id(l)

140415770720072

In [61]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [62]:
id(l)

140415770720072

In [63]:
t = (1, 2, 3)
id(t)

140416059061592

In [64]:
t *= 2
id(t)

140415506085352

## list.sort 与内置函数 sorted

In [65]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [66]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [67]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [68]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [69]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [70]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [71]:
# 就地排序，返回 None
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

## 当列表不适应时

### 数组

#### 创建、保存和加载一个大型浮点数数组

In [72]:
from array import array
from random import random

floats = array('d', (random() for i in range(10 ** 7)))
floats[-1]

0.0026636287230433764

In [73]:
fp = open('floats.bin', 'wb')

In [74]:
floats.tofile(fp)

In [75]:
fp.close()

In [76]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

In [77]:
floats2[-1]

0.0026636287230433764

In [78]:
floats2 == floats

True

### memoryview

#### 分别以 `1*6`、`2*3` 和 `3*2` 矩阵的视图处理 6字节内存

In [79]:
from array import array

octets = array('B', range(6))
m1 = memoryview(octets)
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [80]:
m2 = m1.cast('B', [2, 3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [81]:
m3 = m1.cast('B', [3, 2])
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [82]:
m2[1, 1] = 22
m3[1, 1] = 33
octets

array('B', [0, 1, 2, 33, 22, 5])

In [83]:
# 证明 octets、m1、m2 和 m3 之间的内存是共享的

### Numpy

#### numpy.ndarray 中行和列的基本操作

In [84]:
import numpy as np

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
type(a)

numpy.ndarray

In [86]:
a.shape

(12,)

In [87]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a[2]

array([ 8,  9, 10, 11])

In [89]:
a[2, 1]

9

In [90]:
a[:,1]

array([1, 5, 9])

In [91]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### 加载、保存和操作 numpy.ndarray 对象的所有元素

In [92]:
with open('floats-1M-lines.txt', 'wt') as fp:
    for _ in range(1_000_000):
        fp.write(f'{random()}\n')

In [93]:
floats = np.loadtxt('floats-1M-lines.txt')
floats[-3:]

array([0.81480267, 0.44487581, 0.33107489])

In [94]:
floats *= .5
floats[-3:]

array([0.40740133, 0.22243791, 0.16553745])

In [95]:
from time import perf_counter as pc

t0 = pc(); floats /= 3; pc() - t0

0.0003928749938495457

In [96]:
np.save('floats-1M', floats)

In [97]:
floats2 = np.load('floats-1M.npy', 'r+')
floats2 *= 6
floats2[-3:]

memmap([0.81480267, 0.44487581, 0.33107489])

### 双端队列和其他队列

#### 处理一个 deque 对象

In [98]:
from collections import deque

dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [100]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [101]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [103]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])